name: FileOnQ.Imaging.Raw

on:
  push:
    branches: [ main ]
    tags: [ 'v*', 'v*-preview-*']
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'


    - name: Ensure .NET 5 SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.302

    - name: Ensure .NET 6 SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.101
        
    - name: Install CUDA
      env:
        cuda: 'CUDA-11.4.0'
        visual_studio: 'Visual Studio 16 2019'
      shell: powershell
      run: .\build\cuda.ps1
      
    - name: Check NVCC
      shell: powershell
      run: |
        nvcc -V
        ls $env:CUDA_PATH
        ls $env:CUDA_PATH\bin
        ls $env:CUDA_PATH\include

    - name: Set Version from Tag
      if: startsWith(github.ref, 'refs/tags/v') == true
      run: |
        $version = "${{ github.ref }}" -replace "refs/tags/v", ""
        echo "PACKAGE_VERSION=$version" >> $env:GITHUB_ENV
        echo "Version: $version"

    - name: Set Version
      if: startsWith(github.ref, 'refs/tags/v') == false && ${{ github.event_name != 'pull_request' }}
      run: echo "PACKAGE_VERSION=1.0.0-dev.${{ GITHUB.RUN_NUMBER }}" >> $env:GITHUB_ENV
    
    - name: Set Version for PR
      if: ${{ github.event_name == 'pull_request' }}
      run: echo "PACKAGE_VERSION=1.0.0-pr.${{ GITHUB.RUN_NUMBER }}" >> $env:GITHUB_ENV

    - name: Build
      run: dotnet build -c Release
      working-directory: ./src/FileOnQ.Imaging.Raw
      
    - name: Pack NuGet
      run: dotnet pack -c Release -o ../../ /p:ContinuousIntegrationBuild=true /p:Version=${{ env.PACKAGE_VERSION }} /p:PackageVersion=${{ env.PACKAGE_VERSION }}
      working-directory: ./src/FileOnQ.Imaging.Raw

    - name: Upload NuGet Package
      uses: actions/upload-artifact@v2
      with:
        name: Packages
        path: |
          *.nupkg
          *.snupkg

  test-integration:
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-2019
            architecture: 'AnyCPU'
            framework: 'net48'
          - os: windows-2019
            architecture: 'x86'
            framework: 'net48'
          - os: windows-2019
            architecture: 'x64'
            framework: 'net48'
          - os: windows-2019
            architecture: 'AnyCPU'
            framework: 'net5'
          - os: windows-2019
            architecture: 'x86'
            framework: 'net5'
          - os: windows-2019
            architecture: 'x64'
            framework: 'net5'
          - os: windows-2019
            architecture: 'AnyCPU'
            framework: 'net6'
          - os: windows-2019
            architecture: 'x86'
            framework: 'net6'
          - os: windows-2019
            architecture: 'x64'
            framework: 'net6'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Ensure .NET 5 SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.302

      - name: Ensure .NET 6 SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.101

      - name: Download Artifacts
        uses: actions/download-artifact@v2

      - name: Copy Nupkg
        shell: powershell
        run: Copy-Item Packages\* -Destination .

      - name: Update NuGet
        run: dotnet add package FileOnQ.Imaging.Raw --version ${{ needs.build.outputs.package_version }}
        working-directory: ./tests/FileOnQ.Imaging.Raw.Tests.${{ matrix.architecture }}
      
      - name: Test ${{ matrix.architecture }}
        run: dotnet test -c Release --logger:"console;verbosity=detailed" --filter TestCategory=Integration
        working-directory: ./tests/FileOnQ.Imaging.Raw.Tests.${{ matrix.architecture }}
  test-console-app:
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-2019
            architecture: 'AnyCPU'
            framework: 'net48'
          - os: windows-2019
            architecture: 'x86'
            framework: 'net48'
          - os: windows-2019
            architecture: 'x64'
            framework: 'net48'
          - os: windows-2019
            architecture: 'AnyCPU'
            framework: 'net5'
          - os: windows-2019
            architecture: 'x86'
            framework: 'net5'
          - os: windows-2019
            architecture: 'x64'
            framework: 'net5'
          - os: windows-2019
            architecture: 'AnyCPU'
            framework: 'net6'
          - os: windows-2019
            architecture: 'x86'
            framework: 'net6'
          - os: windows-2019
            architecture: 'x64'
            framework: 'net6'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Ensure .NET 5 SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.302

      - name: Ensure .NET 6 SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.101

      - name: Download Artifacts
        uses: actions/download-artifact@v2
      
      - name: Copy Nupkg
        shell: powershell
        run: Copy-Item Packages\* -Destination .
                
      - name: Update NuGet
        run: dotnet add package FileOnQ.Imaging.Raw --version ${{ needs.build.outputs.package_version }}
        working-directory: ./samples/ConsoleApp/ConsoleApp
        
      - name: Run Console App
        run: dotnet run -c Release
        working-directory: ./samples/ConsoleApp/ConsoleApp

  build-win-forms-app:
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-2019
            architecture: 'AnyCPU'
            framework: 'net48'
          - os: windows-2019
            architecture: 'x86'
            framework: 'net48'
          - os: windows-2019
            architecture: 'x64'
            framework: 'net48'
          - os: windows-2019
            architecture: 'AnyCPU'
            framework: 'net5'
          - os: windows-2019
            architecture: 'x86'
            framework: 'net5'
          - os: windows-2019
            architecture: 'x64'
            framework: 'net5'
          - os: windows-2019
            architecture: 'AnyCPU'
            framework: 'net6'
          - os: windows-2019
            architecture: 'x86'
            framework: 'net6'
          - os: windows-2019
            architecture: 'x64'
            framework: 'net6'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Ensure .NET 5 SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.302

      - name: Ensure .NET 6 SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.101

      - name: Download Artifacts
        uses: actions/download-artifact@v2
      
      - name: Copy Nupkg
        shell: powershell
        run: Copy-Item Packages\* -Destination .
                
      - name: Update NuGet
        run: dotnet add package FileOnQ.Imaging.Raw --version ${{ needs.build.outputs.package_version }}
        working-directory: ./samples/Winforms/Winforms

      - name: Build WinForms App
        run: dotnet build -c Release /p:Platform=${{ matrix.architecture }}
        working-directory: ./samples/Winforms/Winforms